# Header
menu:
  主页 : /
  归档: /archives
  标签&分类: /tags
  关于我: /about
  RSS: /atom.xml 

#logo-wrap
logo_wrap: bili meets hexo
subtitle_wrap: 日常 异常

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: bottom
widgets:
- top_tags
  ##- wangzhantongji
  ##- tagcloud
  ##- recent_posts  ##修改侧边排版
  ##- archive
  ##- category
  ##- tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true 

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
